### PR TITLE
Update to TP11.1

### PR DESCRIPTION
**Pull request by ariedel**
Updates the CGI scripts to TP11.1

### CODE REVIEW

**Review by cdsontag — APPROVED** [review]
Before approval, I ask only that you file a ticket to someday "watch" these files, whether that means changing ssph to run them out of a repo checkout, or setting up a cron job to diff them from a repo checkout, or whatever, is up to you.

**Review by oiintam — APPROVED** [review]
Looks good to me 👍

**Comment by ariedel** [comment]
@cdsontag It should be possible to symlink the cgi scripts to this directory.

**Comment by cdsontag** [comment]
"this directory"  <-  that implies a checkout somewhere, which will have to be git-pulled on occasion

**Comment by cdsontag** [comment]
I'm good with however you want to do it, but if you don't have time to complete the solution today, please file a ticket.

**Comment by ariedel** [comment]
There is a checkout of this repo on both the SSPH machines for the purposes of the SSPH code itself which has to be pulled occasionally, so the CGI scripts can be run out of there.

**Pull request merged**
